version: '3'

services:
  
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - mysql
      - elasticsearch
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=Qwerty.123
      - DB_NAME=prueba
      - ELASTIC_HOST=elasticsearch
    restart: always
    networks:
      - backend
      - external-network

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: Qwerty.123
      MYSQL_DATABASE: prueba
    networks:
      - backend

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      
      - external-network

  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.2
    ports:
      - "5601:5601"
    networks:
      - external-network
    depends_on:
      - elasticsearch
  
  portainer:
    image: portainer/portainer-ce:latest
    ports:
    - "9443:9443"
    restart: unless-stopped
    networks:
      - external-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data



networks:
  backend:
    driver: bridge
  external-network:
    external: true

volumes:
  portainer_data:
  esdata:
    driver: local


