# Dockerfile para la API
FROM python:3.9-slim

# Instalar Tkinter y dependencias si es necesario
RUN apt-get update && apt-get install -y python3-tk libgtk-3-0 libx11-6

WORKDIR /app



# Copiar requirements.txt e instalar dependencias
COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copiar la aplicación
COPY . .

# Exponer puerto 8000 para la API
EXPOSE 8000

CMD [ "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload" ]
